### ISSUE TITLE
Make kicker.jambit.com publicly available

### ISSUE THREAD

**Issue by brennerm** [jambit/malukuBackend#4]
Is there any reason not to do this? From my POV this service does not provide any kind of confidential information.

This would allow colleagues to check the table availability on their way to the office, e.g after lunch.

**Comment by mwerner98** [comment]
I agree with you, it would be definitely interesting to see if a table is available while you're returning after lunch, for example.

Even if the service doesn't provide confidential information (though i admit, that some would argue that. You could theoretically see when someone wants to play, if he uses the list. And other companies could value to know, when jambitees most likely are not working) the bigger issues would be the PI's connected to the sensors an the server itself. Both are a part of our network infrastructure and the internal office network.
If this service would go public, we would open an attack vector to both.
For no the service can be used while being in the building and in reach of our network. For now, if you are returning from lunch for example, you could check your phone on the way to your workplace or the Foosball table.
